"""add position_id to user table

Revision ID: 296b2b43ef35
Revises: 349311908bf2
Create Date: 2026-04-13 14:08:07.445114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '296b2b43ef35'
down_revision = '349311908bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('name', sa.String(length=64), nullable=False, comment='职位名称'),
    sa.Column('post_code', sa.String(length=32), nullable=True, comment='职位编码'),
    sa.Column('level', sa.Integer(), nullable=True, comment='职级，如：1-5级'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态：1=启用, 0=禁用'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='逻辑删除：True=已删除, False=未删除'),
    sa.Column('create_by', sa.String(length=46), nullable=True, comment='创建者'),
    sa.Column('update_by', sa.String(length=46), nullable=True, comment='更新者'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('post_code')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_name'))
        batch_op.drop_index(batch_op.f('ix_posts_post_code'))

    op.drop_table('posts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True, comment='所属岗位ID'))
        batch_op.create_foreign_key(None, 'departments', ['position_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('position_id')

    op.create_table('posts',
    sa.Column('post_code', mysql.VARCHAR(length=64), nullable=False, comment='岗位编码'),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False, comment='岗位名称'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_time', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=False, comment='状态：1=启用, 0=禁用'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='逻辑删除：True=已删除, False=未删除'),
    sa.Column('create_by', mysql.VARCHAR(length=46), nullable=True, comment='创建者'),
    sa.Column('update_by', mysql.VARCHAR(length=46), nullable=True, comment='更新者'),
    sa.Column('remark', mysql.VARCHAR(length=256), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_post_code'), ['post_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_posts_name'), ['name'], unique=False)

    op.drop_table('positions')
    # ### end Alembic commands ###
