"""add avatar to user

Revision ID: 349311908bf2
Revises: 6a55a893be9b
Create Date: 2026-04-10 17:13:23.163443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349311908bf2'
down_revision = '6a55a893be9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True, comment='用户头像URL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
