"""Add fields to Department model: leader

Revision ID: 35c7105ec44d
Revises: 7973860dac18
Create Date: 2026-04-14 11:01:48.789243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35c7105ec44d'
down_revision = '7973860dac18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader', sa.String(length=128), nullable=True, comment='负责人'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('leader')

    # ### end Alembic commands ###
