"""Add fields to Department model: order, leader, phone, email

Revision ID: 7973860dac18
Revises: 296b2b43ef35
Create Date: 2026-04-14 10:50:56.472568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7973860dac18'
down_revision = '296b2b43ef35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False, comment='显示顺序'))
        batch_op.add_column(sa.Column('phone', sa.String(length=32), nullable=True, comment='联系电话'))
        batch_op.add_column(sa.Column('email', sa.String(length=64), nullable=True, comment='邮箱'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'positions', ['position_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_ibfk_2'), 'departments', ['position_id'], ['id'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('order')

    # ### end Alembic commands ###
