"""department add status

Revision ID: 999147c4e58a
Revises: bce57563ef90
Create Date: 2026-04-14 16:04:32.454133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999147c4e58a'
down_revision = 'bce57563ef90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.SmallInteger(), nullable=False, comment='状态：1=启用, 0=禁用'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
