"""Remove status,remark and is_delete from models

Revision ID: bce57563ef90
Revises: 35c7105ec44d
Create Date: 2026-04-14 16:02:18.893129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bce57563ef90'
down_revision = '35c7105ec44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('best_sellers_mattress', schema=None) as batch_op:
        batch_op.drop_column('remark')
        batch_op.drop_column('is_delete')
        batch_op.drop_column('status')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('remark')
        batch_op.drop_column('is_delete')
        batch_op.drop_column('status')

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column('remark')
        batch_op.drop_column('is_delete')
        batch_op.drop_column('status')

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_column('remark')
        batch_op.drop_column('is_delete')
        batch_op.drop_column('status')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('remark')
        batch_op.drop_column('is_delete')
        batch_op.drop_column('status')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('remark')
        batch_op.drop_column('is_delete')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=False, comment='状态：1=启用, 0=禁用'))
        batch_op.add_column(sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='逻辑删除：True=已删除, False=未删除'))
        batch_op.add_column(sa.Column('remark', mysql.VARCHAR(length=256), nullable=True, comment='备注'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=False, comment='状态：1=启用, 0=禁用'))
        batch_op.add_column(sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='逻辑删除：True=已删除, False=未删除'))
        batch_op.add_column(sa.Column('remark', mysql.VARCHAR(length=256), nullable=True, comment='备注'))

    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=False, comment='状态：1=启用, 0=禁用'))
        batch_op.add_column(sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='逻辑删除：True=已删除, False=未删除'))
        batch_op.add_column(sa.Column('remark', mysql.VARCHAR(length=256), nullable=True, comment='备注'))

    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=False, comment='状态：1=启用, 0=禁用'))
        batch_op.add_column(sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='逻辑删除：True=已删除, False=未删除'))
        batch_op.add_column(sa.Column('remark', mysql.VARCHAR(length=256), nullable=True, comment='备注'))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=False, comment='状态：1=启用, 0=禁用'))
        batch_op.add_column(sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='逻辑删除：True=已删除, False=未删除'))
        batch_op.add_column(sa.Column('remark', mysql.VARCHAR(length=256), nullable=True, comment='备注'))

    with op.batch_alter_table('best_sellers_mattress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=False, comment='状态：1=启用, 0=禁用'))
        batch_op.add_column(sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='逻辑删除：True=已删除, False=未删除'))
        batch_op.add_column(sa.Column('remark', mysql.VARCHAR(length=256), nullable=True, comment='备注'))

    # ### end Alembic commands ###
