import React from 'react'
import type {Metadata} from 'next'
import {DM_Sans} from 'next/font/google'
import {Toaster} from 'sonner'
import './css/globals.css'
import {ThemeProvider} from '@/components/theme-provider'
import ServiceWorkerRegister from '@/app/components/service-worker/ServiceWorkerRegister'

const dmSans = DM_Sans({
    subsets: ['latin'],
    display: 'swap',
    // variable: '--font-dm-sans',
    // preload: false,
})

export const metadata: Metadata = {
    title: 'Boss Admin',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en' suppressHydrationWarning data-scroll-behavior='smooth'>
        <head>
            <title/>
            <link rel='icon' href='/favicon.svg' type='image/svg+xml'/>
            <link rel="manifest" href="/manifest.json"/>
            <meta name="theme-color" content="#5d87ff"/>
        </head>
        <body className={`${dmSans.className}`}>
        <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange>
            <ServiceWorkerRegister/>
            {children}
        </ThemeProvider>
        <Toaster richColors position="top-center"/>
        </body>
        </html>
    )
}
